### ISSUE TITLE
Password input field placeholder turns into dots

### ISSUE THREAD

**Issue by phparkle** [elad2412/the-new-css-reset#34]
https://github.com/elad2412/the-new-css-reset/blob/main/css/reset.css#L53

```css
/* reset default text opacity of input placeholder */
::placeholder {
    all: unset;
}
```

This makes the placeholder text in password fields turn into dots. Without the reset it should display as plain text.

It has something to do with the `-webkit-text-security` css property...

**Comment by elad2412** [comment]
Thanks for this important update, it happens in Chrome and Safari (not in Firefox).

I update the style of ```::placeholder``` that it will affect only on text color.

```css
/* reset default text opacity of input placeholder */
::placeholder {
    color: unset;
}
```

Instead of:
```css
/* reset default text opacity of input placeholder */
::placeholder {
    all: unset;
}
```

Updated in the last version of 1.5.0.
I
(Closed Issue)
