### ISSUE TITLE
Add "position: relative" to all elements

### ISSUE THREAD

**Issue by Preciel** [elad2412/the-new-css-reset#37]
By default, all elements are set to `position: static`.

`position: static` and `position:relative` are the same thing, except for the fact that `prosition: static` render the `z-index` property innefective.

Suggested changes :

replace ▼
```css
*,
*::before,
*::after {
    box-sizing: border-box;
}
```
By ▼
```css
* {
    box-sizing: border-box;
    position: relative;
}
*::before,
*::after {
    box-sizing: border-box;
}
```
