### ISSUE TITLE
Strange result with browsers on Windows

### ISSUE THREAD

**Issue by zero2one** [elad2412/the-new-css-reset#39]
I have a strange result with this reset: the `<head> <title>` tag and the content of `<script>` tags within the body are displayed as content in the browser.

This happens only in browsers (tested in Chrome & Edge) on Windows.

I debugged the issue and found out that the error is caused by

```css
*:where(:not(iframe, canvas, img, svg, video):not(svg *, symbol *)) {
  display: revert;
  all: unset;
}
```
