### ISSUE TITLE
Safari requires explicit styling for line-through on <s>

### ISSUE THREAD

**Issue by morganwdavis** [elad2412/the-new-css-reset#40]
Perhaps include this in the README...  I found that I needed to explicitly style the `<s>` element with line-through for Safari.  Just doing a revert (which worked on Chrome) was not enough.

```css
s {
    text-decoration-line: line-through;
}
```
