### ISSUE TITLE
TNCSSR + `-webkit-user-select: none` Breaks Text Input In Safari

### ISSUE THREAD

**Issue by fweth** [elad2412/the-new-css-reset#43]
When setting `-webkit-user-select: none` on the body, I can't type into text input fields in Safari, see [here](https://gufdfx.csb.app/) [(code)](https://codesandbox.io/s/gufdfx).  Not sure what is happening exactly here (in Chrome everything works fine), but it seems related to TNCSSR.  Feel free to delete if this is offtopic.

**Comment by Fasunle** [comment]
Hello,

I don't know what exactly you want to achieve. Could you please provide some more context?

**Comment by fweth** [comment]
When I test the CodeSandbox above on Safari, I can't type text in the input fields.  This seems to only happen
 - on Safari,
 - with `-webkit-user-select: none` activated (e.g. on the body) and
 - TNCSSR imported.
 
Also `user-select: none` does not envoke this behaviour in the Chrome browser.  So I cannot really explain the behaviour, but it seems related to TNCSSR, at least it's not something I would expect to happen when importing the stylesheet.

**Comment by elad2412** [comment]
Hi @fweth,

Sorry for checking it out so late. Added patch to prevent it for hapaning in the new version 1.7.0.

```css
/* Safari - solving issue when using user-select:none on the <body> text input doesn't working */
input ,textarea {
    -webkit-user-select: auto;
}
```

Safaru bug fixed - Issue Closed
