### ISSUE TITLE
`all: revert` on `<pre>` causes unwanted non-zero margins

### ISSUE THREAD

**Issue by wbolster** [elad2412/the-new-css-reset#93]
the `<pre>` element has an unexpected browser-defined non-zero margin b/c of an explicit `revert`.

(almost?) all other elements have no margin, making this an undesired exception. please consider adding `margin`:

``` css
pre {
    all: revert;
    margin: 0;
}
```
